### ISSUE TITLE
WINDOWS10下面 运行失败大佬请指点

### ISSUE THREAD

**Issue by Yan0789** [zhangzhengde0225/HaiChatGPT#4]
WINDOWS10下面 gitclone的您的资源，然后运行提示.apenai/api.text 环境变量里怎么设置呢？大佬请指点。
![微信截图_20230216120907](https://user-images.githubusercontent.com/124667564/219266575-3c6d98e9-400c-41c0-beda-ad2ae168836f.png)

**Comment by zhangzhengde0225** [comment]
在C:\User\A\(也就是你的用户路径)创建.openai文件夹(注意有一个.)，然后文件夹内创建api_key.txt，把你的api_key拷贝进去，保存。

**Comment by Yan0789** [comment]
> 在C:\User\A(也就是你的用户路径)创建.openai文件夹(注意有一个.)，然后文件夹内创建api_key.txt，把你的api_key拷贝进去，保存。

tiktoken安装失败，程序运行不了啊。下面提示啥意思呢？
![tiktoken安装失败](https://user-images.githubusercontent.com/124667564/219303333-f005119d-52cc-48e6-9fc2-9fa689eb99d6.png)
